# SPDX-FileCopyrightText: 2024 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: MIT

image: debian/stable

packages:
  - python3-venv
  - python3-dev
  - pkg-config

sources:
  - https://git.sr.ht/~wombelix/geeko-xlii-cc
  - https://git.sr.ht/~wombelix/build-helper-scripts

secrets:
  - ea615a63-ae64-4e49-adf7-eea1abc09614 # sr.ht builds ansible vault earth-xlii-cc
  - 8c7583f6-3858-4f9b-a72d-3e3bd952d65b # sr.ht builds ssh key earth.xlii.cc
  - 5b076ab5-1361-4d71-905b-4ff8c836c62c # sr.ht builds git mirror deploy key

environment:
  GIT_MIRROR_SSH_KEY: ~/.ssh/5b076ab5-1361-4d71-905b-4ff8c836c62c
  GIT_MIRROR_GITHUB: git@github.com:wombelix/geeko-xlii-cc.git
  GIT_MIRROR_GITLAB: git@gitlab.com:wombelix/geeko-xlii-cc.git
  GIT_MIRROR_CODEBERG: git@codeberg.org:wombelix/geeko-xlii-cc.git

tasks:
  - mirror: |
      cd build-helper-scripts
      source git-mirror.sh
      cd ..

      cd geeko-xlii-cc

      git_mirror "$GIT_MIRROR_SSH_KEY" "$GIT_MIRROR_GITHUB"
      git_mirror "$GIT_MIRROR_SSH_KEY" "$GIT_MIRROR_GITLAB"
      git_mirror "$GIT_MIRROR_SSH_KEY" "$GIT_MIRROR_CODEBERG"

  - setup: |
      cd geeko-xlii-cc
      python3 -m venv venv
      source venv/bin/activate
      python3 -m pip install --upgrade pip
      python3 -m pip install -r requirements.txt
      # ansible.cfg expects vault password file in same directory
      ln -s ~/.secret_vault .secret_vault
      # Install ansible collections and roles first, otherwise ansible-lint will fail
      # https://github.com/ansible/ansible-lint/issues/3636
      ansible-galaxy collection install -v --pre -r collections/requirements.yml
      ansible-galaxy role install -v -r roles/requirements.yml
      # Only trust known geeko.xlii.cc SSH fingerprints
      cp files/ssh_fingerprints_geeko_xlii_cc.txt ~/.ssh/known_hosts

  - check: |
      cd geeko-xlii-cc
      source venv/bin/activate
      ansible-lint

  - ansible: |
      cd geeko-xlii-cc
      source venv/bin/activate
      ansible-playbook --vault-password-file ~/.secret_vault site.yml

triggers:
  - action: email
    condition: failure
    to: dominik@wombacher.cc
