# SPDX-FileCopyrightText: 2024 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: MIT

---
- name: Entrypoint to run all playbooks
  hosts: all
  become: false
  gather_facts: false
  no_log: true
...
